# DO NOT EDIT THIS FILE!
#
# Python module org__POA.fimproso generated by omniidl

import omniORB
omniORB.updateModule("org__POA.fimproso")

# ** 1. Stub files contributing to this module
import OperationsBancaires_idl

# ** 2. Sub-modules

# ** 3. End
