# Python stubs generated by omniidl from OperationsBancaires.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "org"
#
__name__ = "org"
_0_org = omniORB.openModule("org", r"OperationsBancaires.idl")
_0_org__POA = omniORB.openModule("org__POA", r"OperationsBancaires.idl")


#
# Start of module "org.fimproso"
#
__name__ = "org.fimproso"
_0_org.fimproso = omniORB.openModule("org.fimproso", r"OperationsBancaires.idl")
_0_org__POA.fimproso = omniORB.openModule("org__POA.fimproso", r"OperationsBancaires.idl")


# interface OperationBancaire
_0_org.fimproso._d_OperationBancaire = (omniORB.tcInternal.tv_objref, "IDL:org/fimproso/OperationBancaire:1.0", "OperationBancaire")
omniORB.typeMapping["IDL:org/fimproso/OperationBancaire:1.0"] = _0_org.fimproso._d_OperationBancaire
_0_org.fimproso.OperationBancaire = omniORB.newEmptyClass()
class OperationBancaire :
    _NP_RepositoryId = _0_org.fimproso._d_OperationBancaire[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_org.fimproso.OperationBancaire = OperationBancaire
_0_org.fimproso._tc_OperationBancaire = omniORB.tcInternal.createTypeCode(_0_org.fimproso._d_OperationBancaire)
omniORB.registerType(OperationBancaire._NP_RepositoryId, _0_org.fimproso._d_OperationBancaire, _0_org.fimproso._tc_OperationBancaire)

# OperationBancaire operations and attributes
OperationBancaire._d_balance = ((), (omniORB.tcInternal.tv_double, ), None)
OperationBancaire._d_depot = ((omniORB.tcInternal.tv_double, ), (), None)
OperationBancaire._d_retrait = ((omniORB.tcInternal.tv_double, ), (), None)

# OperationBancaire object reference
class _objref_OperationBancaire (CORBA.Object):
    _NP_RepositoryId = OperationBancaire._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def balance(self, *args):
        return self._obj.invoke("balance", _0_org.fimproso.OperationBancaire._d_balance, args)

    def depot(self, *args):
        return self._obj.invoke("depot", _0_org.fimproso.OperationBancaire._d_depot, args)

    def retrait(self, *args):
        return self._obj.invoke("retrait", _0_org.fimproso.OperationBancaire._d_retrait, args)

omniORB.registerObjref(OperationBancaire._NP_RepositoryId, _objref_OperationBancaire)
_0_org.fimproso._objref_OperationBancaire = _objref_OperationBancaire
del OperationBancaire, _objref_OperationBancaire

# OperationBancaire skeleton
__name__ = "org__POA.fimproso"
class OperationBancaire (PortableServer.Servant):
    _NP_RepositoryId = _0_org.fimproso.OperationBancaire._NP_RepositoryId


    _omni_op_d = {"balance": _0_org.fimproso.OperationBancaire._d_balance, "depot": _0_org.fimproso.OperationBancaire._d_depot, "retrait": _0_org.fimproso.OperationBancaire._d_retrait}

OperationBancaire._omni_skeleton = OperationBancaire
_0_org__POA.fimproso.OperationBancaire = OperationBancaire
omniORB.registerSkeleton(OperationBancaire._NP_RepositoryId, OperationBancaire)
del OperationBancaire
__name__ = "org.fimproso"

#
# End of module "org.fimproso"
#
__name__ = "org"


#
# End of module "org"
#
__name__ = "OperationsBancaires_idl"

_exported_modules = ( "org", "org.fimproso")

# The end.
