package org.fimproso;


/**
* org/fimproso/OperationBancaireHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* samedi 20 décembre 2025 20 h 12 CAT
*/

abstract public class OperationBancaireHelper
{
  private static String  _id = "IDL:org/fimproso/OperationBancaire:1.0";

  public static void insert (org.omg.CORBA.Any a, org.fimproso.OperationBancaire that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.fimproso.OperationBancaire extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.fimproso.OperationBancaireHelper.id (), "OperationBancaire");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.fimproso.OperationBancaire read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperationBancaireStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.fimproso.OperationBancaire value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.fimproso.OperationBancaire narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.fimproso.OperationBancaire)
      return (org.fimproso.OperationBancaire)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.fimproso._OperationBancaireStub stub = new org.fimproso._OperationBancaireStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.fimproso.OperationBancaire unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.fimproso.OperationBancaire)
      return (org.fimproso.OperationBancaire)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.fimproso._OperationBancaireStub stub = new org.fimproso._OperationBancaireStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
