package org.fimproso;


/**
* org/fimproso/OperationBancaireOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* samedi 20 décembre 2025 20 h 12 CAT
*/

public interface OperationBancaireOperations 
{
  double balance ();
  void depot (double amount);
  void retrait (double amount);
} // interface OperationBancaireOperations
