package org.fimproso;

/**
* org/fimproso/OperationBancaireHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* samedi 20 décembre 2025 20 h 12 CAT
*/

public final class OperationBancaireHolder implements org.omg.CORBA.portable.Streamable
{
  public org.fimproso.OperationBancaire value = null;

  public OperationBancaireHolder ()
  {
  }

  public OperationBancaireHolder (org.fimproso.OperationBancaire initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.fimproso.OperationBancaireHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.fimproso.OperationBancaireHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.fimproso.OperationBancaireHelper.type ();
  }

}
