package org.fimproso;


/**
* org/fimproso/OperationBancaire.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* samedi 20 décembre 2025 20 h 12 CAT
*/

public interface OperationBancaire extends OperationBancaireOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OperationBancaire
